spring.application.name=blog

spring.datasource.url=jdbc:postgresql://ep-broad-voice-agw5hhil-pooler.c-2.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_fYzDuyU0I9OZ&sslmode=require&channelBinding=require
spring.datasource.username=postgres
spring.datasource.password=npg_fYzDuyU0I9OZ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
